spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/examdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show_sql: true

server:
  port: 8080